#基础镜像
FROM centos:7
#作者信息
MAINTAINER 吴文付 <hi_php@163.com>

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo 'Asia/Shanghai' >/etc/timezone



#更新源. 安装php56
USER root


RUN yum  install -y epel-release
RUN rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum install -y --enablerepo=remi --enablerepo=remi-php56 php php-fpm php-opcache php-devel php-mbstring \
php-mcrypt php-mysqlnd php-pdo php-mysqli php-phpunit-PHPUnit php-pecl-xdebug php-pecl-xhprof php-gd php-redis php-memcache php-amqp


#安装 composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer 


#安装nginx
RUN yum install -y nginx


#php的配置文件。
ADD conf/php.ini  /etc/
ADD conf/www.conf /etc/php-fpm.d/


#nginx的配置
ADD conf/nginx.conf  /etc/nginx/
ADD conf/conf.d/*  /etc/nginx/conf.d/

#php的日志需要读写权限
RUN chmod 777 /var/log/php-fpm/www-error.log

#开发端口 
EXPOSE 80 9000


