#基础镜像
FROM centos:7
#作者信息
MAINTAINER 吴文付 <hi_php@163.com>

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo 'Asia/Shanghai' >/etc/timezone



#更新源. 安装php7
USER root


RUN yum  install -y epel-release
RUN yum install -y http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

#安装nginx
RUN yum install -y nginx

RUN yum install -y gcc
RUN yum install -y cmake


RUN rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm


RUN yum install -y php70w php70w-fpm php70w-opcache php70w-devel php70w-mbstring \
php70w-mcrypt php70w-mysqlnd php70w-pdo php70w-mysqli php70w-php70wunit-PHPUnit php70w-pecl-xdebug \ php70w-pecl-xhprof php70w-gd php70w-pecl-redis php70w-pecl-memcache


RUN yum install -y php70-php-pecl-amqp.x86_64


#安装 composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer 



RUN pecl install swoole


#配置文件
#php的配置文件。
ADD conf/php.ini  /etc/
#php-fpm的配置
ADD conf/www.conf /etc/php-fpm.d/

#nginx的配置
ADD conf/nginx.conf  /etc/nginx/
#站点的配置
ADD conf/conf.d/*  /etc/nginx/conf.d/



#开发端口 
EXPOSE 80 9000 443 9501 9502 9503


