#基础镜像
FROM centos:7
#作者信息
MAINTAINER 吴文付 <hi_php@163.com>

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo 'Asia/Shanghai' >/etc/timezone

#更新源.
USER root
RUN yum -y install gcc automake autoconf libtool make


#备份
RUN mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
RUN curl -O http://mirrors.163.com/.help/CentOS7-Base-163.repo 
RUN mv CentOS7-Base-163.repo /etc/yum.repos.d/
RUN yum clean all
RUN yum makecache

#安装php

RUN yum  install -y epel-release
RUN rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

RUN yum install -y --enablerepo=remi --enablerepo=remi-php56 php-fpm php-opcache php-devel php-mbstring \
php-mcrypt php-mysqlnd php-pdo php-mysqli php-phpunit-PHPUnit php-pecl-xdebug php-pecl-xhprof php-gd php-redis php-memcache php-amqp


#安装 composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer 
#中国镜像
RUN composer config -g repo.packagist composer https://packagist.phpcomposer.com

#安装swoole
RUN pecl install swoole


#配置文件 增加swoole.so的开启
RUN  echo extension=swoole.so >> /etc/php.ini
